version: '3'
services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    command: sh -c "rabbitmq-plugins enable rabbitmq_management; rabbitmq-server"
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "8080:8080"
    networks:
      - planet-express-network
    volumes:
      - ./deploy/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - planet-express-network
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    networks:
      - planet-express_planet-express-network
networks:
  planet-express-network:
    driver: bridge
