version: '3'
services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    command: sh -c "rabbitmq-plugins enable rabbitmq_management; rabbitmq-server"
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "8080:8080"
    networks:
      - planet-express-network
    volumes:
      - ./deploy/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - planet-express-network
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    networks:
      - planet-express-network
  planet-express:
    image: koalacorp/planet-express:development
    command: sh -c "cd /crawlers/ceuta/ceuta && (scrapy crawl elfarodeceuta & scrapy crawl elpueblodeceuta)"
    container_name: planet-express
    hostname: planet-express
    networks:
      - planet-express-network
  planet-express-42:
    image: koalacorp/planet-express-42:development
    command: sh -c "cd /worker && (python worker.py elfarodeceuta & python worker.py elpueblodeceuta)"
    container_name: planet-express-42
    hostname: planet-express-42
    networks:
      - planet-express-network
  planet-express-abe:
    image: planet-express-abe:development
    command: sh -c "cd /api && python api_rest.py"
    container_name: planet-express-abe
    hostname: planet-express-abe
    ports:
      - "5000:5000"
    networks:
      - planet-express-network
networks:
  planet-express-network:
    driver: bridge
