version: '3'
services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    command: sh -c "rabbitmq-plugins enable rabbitmq_management; rabbitmq-server"
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "8080:8080"
    volumes:
      - ./configuration/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
  planet-express:
    image: koalacorp/planet-express:development
    command: sh -c "cd /crawlers/ceuta/ceuta && scrapy crawl elfarodeceuta"
    container_name: planet-express
    hostname: planet-express
    depends_on:
      - redis
      - rabbitmq
  planet-express-42:
    image: koalacorp/planet-express-42:development
    command: sh -c "cd /worker && python worker.py elfarodeceuta"
    container_name: planet-express-42
    hostname: planet-express-42
    depends_on:
      - mongo
      - rabbitmq
  planet-express-abe:
    image: koalacorp/planet-express-abe:development
    command: sh -c "cd /api && python populate.py && python api_rest.py"
    container_name: planet-express-abe
    hostname: planet-express-abe
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  planet-express-hawkeye:
    image: koalacorp/planet-express-hawkeye:development
    command: sh -c "yarn dev"
    container_name: planet-express-hawkeye
    hostname: planet-express-hawkeye
    ports:
      - "80:8080"
    depends_on:
      - planet-express-abe
