apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "crawler-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "crawler-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}          
    spec:
      containers:
        - name: crawler
          image: "crawler"
          imagePullPolicy: "Never"
          env:
          - name: REDIS_HOST
            value: "redis-service"
          - name: REDIS_PORT
            value: "6379"
          - name: RABBITMQ_HOST
            value: "rabbitmq-service"
          - name: RABBITMQ_PORT
            value: "5672"

