apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "redis-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: redis
        app.kubernetes.io/name: {{ include "redis-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}          
    spec:
      containers:
        - name: redis
          image: "redis"
