apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "worker-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "worker-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}          
    spec:
      containers:
        - name: worker
          image: "koalacorp/planet-express-worker"
          env:
          - name: RABBITMQ_HOST
            value: "rabbitmq-service"
          - name: RABBITMQ_PORT
            value: "5672"

